In [ ]:
!python --version

Python 3.8.17

In [ ]:
!pip install recommenders

In [ ]:
import sys
from recommenders.models.tfidf.tfidf_utils import TfidfRecommender

# Print version
print("System version: {}".format(sys.version))

System version: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]

In [2]:
import pandas as pd

In [4]:
df=pd.read_table('outcomes.tsv')
df.head()

,auction_id,product_id,item,desc,retail,price,finalprice,bidincrement,bidfee,winner,placedbids,freebids,endtime_str,flg_click_only,flg_beginnerauction,flg_fixedprice,flg_endprice
0,86827,10009602,sony-ericsson-s500i-unlocked-mysterious-,Sony Ericsson S500i Unlocked Mysterious Green,499.99,13.35,13.35,15,75,Racer11,26,0,19:52 PDT 09-16-2008,0,0,0,0
1,87964,10009881,psp-slim-lite-sony-piano-black,PSP Slim & Lite Sony Piano Black,169.99,74.70,74.70,15,75,Cemo23,65,0,11:17 PDT 08-28-2008,0,0,0,0
2,87965,10009881,psp-slim-lite-sony-piano-black,PSP Slim & Lite Sony Piano Black,169.99,83.10,83.10,15,75,Jacobsonnich,94,0,22:52 PDT 11-07-2008,0,1,0,0
3,88638,10006115,sony-ericsson-s500i-unlocked-mysterious-,Sony Ericsson S500i Unlocked Mysterious Green,499.99,19.65,19.65,15,75,Mokkis,10,0,22:02 PDT 08-23-2008,0,0,0,0
4,88639,10006115,sony-ericsson-s500i-unlocked-mysterious-,Sony Ericsson S500i Unlocked Mysterious Green,499.99,47.10,47.10,15,75,Superloeffel,80,0,14:23 PDT 08-24-2008,0,0,0,0

In [ ]:
df.shape

(121419, 17)

In [ ]:
df.product_id.value_counts()

10012220    6658
10006485    5893
10011707    3283
10011706    2365
10009318    2297
            ...
10013942       1
10011465       1
10009745       1
10013288       1
10009933       1
Name: product_id, Length: 2081, dtype: int64

In [ ]:
df1=df.groupby(df.product_id).first().reset_index()
df1.head()

,product_id,auction_id,item,desc,retail,price,finalprice,bidincrement,bidfee,winner,placedbids,freebids,endtime_str,flg_click_only,flg_beginnerauction,flg_fixedprice,flg_endprice
0,10001093,178221,cuisinart-cjk-17bc-cordless-electric-jug,Cuisinart CJK-17BC Cordless Electric Jug Kettle,130.0,43.05,43.05,15,75,Midiadisplay,107,0,10:03 PDT 05-15-2009,0,0,0,0
1,10001577,96718,calvin-klein-ck-one-6-7oz-eau-de-toilett,Calvin Klein CK One 6.7oz Eau De Toilette Spray,50.0,15.90,15.90,15,75,Gorlitz123,21,0,05:12 PDT 08-29-2008,0,0,0,0
2,10002392,178224,cuisinart-classic-brushed-chrome-toaster,"Cuisinart Classic Brushed Chrome Toaster, 2-Slice",110.0,62.85,62.85,15,75,Pinsel7,87,0,08:58 PDT 05-17-2009,0,0,0,0
3,10002407,94876,300-freebids-voucher,300 FreeBids Voucher,300.0,108.60,0.00,15,75,Daveo140,16,0,21:20 PDT 08-25-2008,0,0,0,1
4,10002689,96683,lavazza-crema-aroma-coffee-beans-12-x-2-,Lavazza Crema & Aroma Coffee Beans 12 x 2.2lb,330.0,24.15,0.00,15,75,schweihei,51,0,04:32 PDT 08-29-2008,0,0,0,1

In [ ]:
df1.shape

(2081, 17)

In [ ]:
#use scibert
recommender=TfidfRecommender(id_col='product_id',tokenization_method='scibert')

In [ ]:
cols_to_clean=['desc']
clean_col='cleaned_text'
df_clean=recommender.clean_dataframe(df1,cols_to_clean,clean_col)
df_clean

,product_id,auction_id,item,desc,retail,price,finalprice,bidincrement,bidfee,winner,placedbids,freebids,endtime_str,flg_click_only,flg_beginnerauction,flg_fixedprice,flg_endprice,cleaned_text
0,10001093,178221,cuisinart-cjk-17bc-cordless-electric-jug,Cuisinart CJK-17BC Cordless Electric Jug Kettle,130.00,43.05,43.05,15,75,Midiadisplay,107,0,10:03 PDT 05-15-2009,0,0,0,0,Cuisinart CJK17BC Cordless Electric Jug Kettle
1,10001577,96718,calvin-klein-ck-one-6-7oz-eau-de-toilett,Calvin Klein CK One 6.7oz Eau De Toilette Spray,50.00,15.90,15.90,15,75,Gorlitz123,21,0,05:12 PDT 08-29-2008,0,0,0,0,Calvin Klein CK One 67oz Eau De Toilette Spray
2,10002392,178224,cuisinart-classic-brushed-chrome-toaster,"Cuisinart Classic Brushed Chrome Toaster, 2-Slice",110.00,62.85,62.85,15,75,Pinsel7,87,0,08:58 PDT 05-17-2009,0,0,0,0,Cuisinart Classic Brushed Chrome Toaster 2Slice
3,10002407,94876,300-freebids-voucher,300 FreeBids Voucher,300.00,108.60,0.00,15,75,Daveo140,16,0,21:20 PDT 08-25-2008,0,0,0,1,300 FreeBids Voucher
4,10002689,96683,lavazza-crema-aroma-coffee-beans-12-x-2-,Lavazza Crema & Aroma Coffee Beans 12 x 2.2lb,330.00,24.15,0.00,15,75,schweihei,51,0,04:32 PDT 08-29-2008,0,0,0,1,Lavazza Crema Aroma Coffee Beans 12 x 22lb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2076,10015338,253351,sony-playstation-3-slim-250gb-50-bids,Sony PlayStation 3 Slim 250GB + 50 Bids,379.99,221.64,221.64,12,60,Hansen00,164,0,16:53 PDT 12-02-2009,0,0,0,0,Sony PlayStation 3 Slim 250GB 50 Bids
2077,10015340,253427,apple-iphone-3gs-32gb-black-150-bids,Apple iPhone 3GS 32GB Black+ 150 Bids,988.00,16.78,16.78,1,60,Jarop,323,173,01:56 PDT 12-03-2009,0,0,0,0,Apple iPhone 3GS 32GB Black 150 Bids
2078,10015377,256434,jvc-picsio-gc-fm1a-hd-camcorder-black-ic,JVC PICSIO GC-FM1A HD Camcorder (Black Ice),219.99,13.32,13.32,12,60,nathan1994,47,0,02:00 PDT 12-09-2009,0,0,0,0,JVC PICSIO GCFM1A HD Camcorder Black Ice
2079,10015387,256940,apple-iphone-3gs-32gb-black-200-freebids,Apple iPhone 3GS 32GB Black + 200 FreeBids,1018.00,30.87,30.87,1,60,Neverquits1,449,0,18:21 PDT 12-07-2009,0,0,0,0,Apple iPhone 3GS 32GB Black 200 FreeBids
2080,10015477,255628,god-of-war-collection-ps3-,God of War Collection (PS3),39.99,25.32,25.32,12,60,Aggrome,19,0,19:05 PDT 12-10-2009,0,0,0,0,God of War Collection PS3

In [ ]:
df_clean.shape

(2081, 18)

In [ ]:
print(df_clean[clean_col][0][:1000])

Cuisinart CJK17BC Cordless Electric Jug Kettle

In [ ]:
tf, vectors_tokenized = recommender.tokenize_text(df_clean, text_col=clean_col)

In [ ]:
recommender.fit(tf, vectors_tokenized)

top_k_recommendations = recommender.recommend_top_k_items(df_clean, k=5)

In [ ]:
top_k_recommendations

       product_id  rec_rank  rec_score  rec_product_id
0        10001093         1   0.316381        10011173
1        10001093         2   0.288073        10015115
2        10001093         3   0.196876        10013238
3        10001093         4   0.191393        10014570
4        10001093         5   0.172641        10012253
...           ...       ...        ...             ...
10400    10015477         1   0.114375        10010716
10401    10015477         2   0.104354        10011038
10402    10015477         3   0.100872        10014797
10403    10015477         4   0.100702        10013992
10404    10015477         5   0.096199        10010435

[10405 rows x 4 columns]

In [ ]:
full_rec_list=recommender.recommendations
product_of_interest=10001093
print('Number of recommended product for ' + str(product_of_interest) + ': ' + str(len(full_rec_list[product_of_interest])))

Number of recommended product for 10001093: 2080

In [ ]:
tokens = recommender.get_tokens()
print(list(tokens.keys())[:10])

['cu', 'isi', 'nar', 'cj', '17', 'bc', 'cord', 'electric', 'jug', 'ket']

In [ ]:
stop_words=list(recommender.get_stop_words())
stop_words.sort()
print(stop_words[:10])

['a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'all', 'almost']

In [ ]:
cols_to_keep=['item','desc']
recommender.get_top_k_recommendations(df1,product_of_interest,cols_to_keep)

,rank,similarity_score,item,desc
0,1,0.316381,cuisinart-cordless-automatic-electric-ke,Cuisinart Cordless Automatic Electric Kettle
1,2,0.288073,cuisinart-red-teakettle,Cuisinart Red Teakettle
2,3,0.196876,cuisinart-cleanwater-filtration-system,Cuisinart CleanWater Filtration System
3,4,0.191393,cuisinart-white-hand-blender,Cuisinart White Hand Blender
4,5,0.172641,cuisinart-mini-prep-plus-4-cup-food-proc,Cuisinart Mini-Prep Plus 4-Cup Food Processor

In [ ]:
full_rec_list=recommender.recommendations
product_of_interest=10015477
print('Number of recommended product for ' + str(product_of_interest) + ': ' + str(len(full_rec_list[product_of_interest])))

Number of recommended product for 10015477: 2080

In [ ]:
cols_to_keep=['item','desc']
recommender.get_top_k_recommendations(df1,product_of_interest,cols_to_keep)

,rank,similarity_score,item,desc
0,1,0.114375,star-wars-the-clone-wars-jedi-alliance-d,Star Wars The Clone Wars: Jedi Alliance (DS)
1,2,0.104354,star-wars-the-clone-wars-lightsaber-duel,Star Wars The Clone Wars: Lightsaber Duels (Wii)
2,3,0.100872,star-wars-the-clone-wars-republic-heroes,Star Wars: The Clone Wars - Republic Heroes (PC)
3,4,0.100702,star-wars-the-clone-wars-republic-heroes,Star Wars: The Clone Wars - Republic Heroes (Wii)
4,5,0.096199,sony-psp-god-of-war-entertainment-pack-r,Sony PSP God of War Entertainment Pack - Red

In [ ]:
#use BERT
recommender1=TfidfRecommender(id_col='product_id',tokenization_method='bert')

In [ ]:
cols_to_clean1=['desc']
clean_col1='cleaned_text'
df_clean1=recommender1.clean_dataframe(df1,cols_to_clean1,clean_col1)
df_clean1

,product_id,auction_id,item,desc,retail,price,finalprice,bidincrement,bidfee,winner,placedbids,freebids,endtime_str,flg_click_only,flg_beginnerauction,flg_fixedprice,flg_endprice,cleaned_text
0,10001093,178221,cuisinart-cjk-17bc-cordless-electric-jug,Cuisinart CJK-17BC Cordless Electric Jug Kettle,130.00,43.05,43.05,15,75,Midiadisplay,107,0,10:03 PDT 05-15-2009,0,0,0,0,Cuisinart CJK17BC Cordless Electric Jug Kettle
1,10001577,96718,calvin-klein-ck-one-6-7oz-eau-de-toilett,Calvin Klein CK One 6.7oz Eau De Toilette Spray,50.00,15.90,15.90,15,75,Gorlitz123,21,0,05:12 PDT 08-29-2008,0,0,0,0,Calvin Klein CK One 67oz Eau De Toilette Spray
2,10002392,178224,cuisinart-classic-brushed-chrome-toaster,"Cuisinart Classic Brushed Chrome Toaster, 2-Slice",110.00,62.85,62.85,15,75,Pinsel7,87,0,08:58 PDT 05-17-2009,0,0,0,0,Cuisinart Classic Brushed Chrome Toaster 2Slice
3,10002407,94876,300-freebids-voucher,300 FreeBids Voucher,300.00,108.60,0.00,15,75,Daveo140,16,0,21:20 PDT 08-25-2008,0,0,0,1,300 FreeBids Voucher
4,10002689,96683,lavazza-crema-aroma-coffee-beans-12-x-2-,Lavazza Crema & Aroma Coffee Beans 12 x 2.2lb,330.00,24.15,0.00,15,75,schweihei,51,0,04:32 PDT 08-29-2008,0,0,0,1,Lavazza Crema Aroma Coffee Beans 12 x 22lb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2076,10015338,253351,sony-playstation-3-slim-250gb-50-bids,Sony PlayStation 3 Slim 250GB + 50 Bids,379.99,221.64,221.64,12,60,Hansen00,164,0,16:53 PDT 12-02-2009,0,0,0,0,Sony PlayStation 3 Slim 250GB 50 Bids
2077,10015340,253427,apple-iphone-3gs-32gb-black-150-bids,Apple iPhone 3GS 32GB Black+ 150 Bids,988.00,16.78,16.78,1,60,Jarop,323,173,01:56 PDT 12-03-2009,0,0,0,0,Apple iPhone 3GS 32GB Black 150 Bids
2078,10015377,256434,jvc-picsio-gc-fm1a-hd-camcorder-black-ic,JVC PICSIO GC-FM1A HD Camcorder (Black Ice),219.99,13.32,13.32,12,60,nathan1994,47,0,02:00 PDT 12-09-2009,0,0,0,0,JVC PICSIO GCFM1A HD Camcorder Black Ice
2079,10015387,256940,apple-iphone-3gs-32gb-black-200-freebids,Apple iPhone 3GS 32GB Black + 200 FreeBids,1018.00,30.87,30.87,1,60,Neverquits1,449,0,18:21 PDT 12-07-2009,0,0,0,0,Apple iPhone 3GS 32GB Black 200 FreeBids
2080,10015477,255628,god-of-war-collection-ps3-,God of War Collection (PS3),39.99,25.32,25.32,12,60,Aggrome,19,0,19:05 PDT 12-10-2009,0,0,0,0,God of War Collection PS3

In [ ]:
tf, vectors_tokenized = recommender1.tokenize_text(df_clean1, text_col=clean_col1)

In [ ]:
recommender1.fit(tf, vectors_tokenized)

top_k_recommendations1 = recommender1.recommend_top_k_items(df_clean1, k=5)

In [ ]:
top_k_recommendations1

       product_id  rec_rank  rec_score  rec_product_id
0        10001093         1   0.344605        10011173
1        10001093         2   0.202784        10014570
2        10001093         3   0.195044        10012253
3        10001093         4   0.188052        10015115
4        10001093         5   0.187337        10013238
...           ...       ...        ...             ...
10400    10015477         1   0.257855        10010825
10401    10015477         2   0.257855        10010435
10402    10015477         3   0.257855        10010854
10403    10015477         4   0.085429        10011411
10404    10015477         5   0.084754        10011111

[10405 rows x 4 columns]

In [ ]:
full_rec_list1=recommender1.recommendations
product_of_interest1=10001093
print('Number of recommended product for ' + str(product_of_interest1) + ': ' + str(len(full_rec_list1[product_of_interest1])))

Number of recommended product for 10001093: 2080

In [ ]:
tokens1 = recommender1.get_tokens()
print(list(tokens1.keys())[:10])

['ui', 'sin', 'art', '17', 'bc', 'rd', 'electric', 'ju', 'ke', 'ttle']

In [ ]:
cols_to_keep1=['item','desc']
recommender1.get_top_k_recommendations(df1,product_of_interest1,cols_to_keep1)

,rank,similarity_score,item,desc
0,1,0.344605,cuisinart-cordless-automatic-electric-ke,Cuisinart Cordless Automatic Electric Kettle
1,2,0.202784,cuisinart-white-hand-blender,Cuisinart White Hand Blender
2,3,0.195044,cuisinart-mini-prep-plus-4-cup-food-proc,Cuisinart Mini-Prep Plus 4-Cup Food Processor
3,4,0.188052,cuisinart-red-teakettle,Cuisinart Red Teakettle
4,5,0.187337,cuisinart-cleanwater-filtration-system,Cuisinart CleanWater Filtration System

In [ ]:
full_rec_list1=recommender1.recommendations
product_of_interest1=10015477
print('Number of recommended product for ' + str(product_of_interest1) + ': ' + str(len(full_rec_list1[product_of_interest1])))

Number of recommended product for 10015477: 2080

In [ ]:
cols_to_keep1=['item','desc']
recommender1.get_top_k_recommendations(df1,product_of_interest1,cols_to_keep1)

,rank,similarity_score,item,desc
0,1,0.257855,sony-psp-god-of-war-entertainment-pack-r,Sony PSP God of War Entertainment Pack - Red
1,2,0.257855,sony-psp-god-of-war-entertainment-pack-r,Sony PSP God of War Entertainment Pack - Red
2,3,0.257855,sony-psp-god-of-war-entertainment-pack-r,Sony PSP God of War Entertainment Pack - Red
3,4,0.085429,gears-of-war-2-xbox-360-,Gears of War 2 (Xbox 360)
4,5,0.084754,call-of-duty-world-at-war-pc-,Call of Duty: World at War (PC)

In [ ]:
#use BERT more accuracy

In [6]:
df1=pd.read_table('traces.tsv')
df1.head()

,auction_id,bid_time,bid_ct,bid_number,bid_user,bid_butler,bid_cp,bid_user_secs_added,bid_butler_secs_added,bid_infered,bid_group,bid_final
0,222387,2009-10-04 12:33:26,19913,1,Becker1990,0,12,0,0,0,0,0
1,222387,2009-10-04 14:28:14,13029,2,Gaynor66,0,24,4,0,0,1,0
2,222387,2009-10-04 14:44:08,12079,3,Jostrem16,0,36,4,0,0,2,0
3,222387,2009-10-04 17:14:26,3071,4,Clubfan78,0,48,10,0,0,3,0
4,222387,2009-10-04 17:36:06,1773,5,Momstired2,0,60,2,0,0,4,0

In [11]:
df2=df1.drop_duplicates(subset=['auction_id','bid_user']).groupby('bid_user').size().sort_values(ascending=False)#.reset_index()
df2

bid_user
Lillyblitz    258
Npr1967       225
Drodenbeck    214
Zwerg1953     191
Varis         191
             ...
Keebler87       1
Kedii           1
Kebo178         1
Keber314        1
zzindy          1
Length: 60537, dtype: int64

In [15]:
df2[df2==5]

bid_user
Salimin2        5
Joshua982       5
Phatpharm       5
Joshthegreat    5
Minhly12        5
               ..
Sangninja       5
01a04w81        5
Pkaye33         5
Baseballdude    5
Boredndsm       5
Length: 3008, dtype: int64

In [21]:
df3 = df1[df1.bid_user=='Joshua982'].sort_values('bid_time').drop_duplicates(subset='auction_id', keep='first')
df3

,auction_id,bid_time,bid_ct,bid_number,bid_user,bid_butler,bid_cp,bid_user_secs_added,bid_butler_secs_added,bid_infered,bid_group,bid_final
1076612,239260,2009-10-27 06:30:10,4160,4,Joshua982,0,48,5,0,0,3,0
902023,236098,2009-10-27 17:53:01,20,488,Joshua982,0,2928,3,0,0,379,0
1083602,239318,2009-10-27 17:59:04,20,146,Joshua982,0,1752,0,0,1,116,0
901475,236097,2009-10-27 19:56:21,20,935,Joshua982,0,5610,0,0,0,418,0
902826,236099,2009-10-27 20:10:34,20,57,Joshua982,0,342,0,0,0,35,0

In [38]:
import numpy as np
negative = np.random.choice(df1.auction_id.unique(), 20)
' '.join([f'{x}-0' for x in negative])

'252893-0 233372-0 231439-0 250036-0 229185-0 224274-0 230242-0 242493-0 234036-0 253464-0 227817-0 252242-0 222528-0 240944-0 227753-0 250421-0 228028-0 242956-0 247804-0 242447-0'

In [25]:
print(' '.join(df3.auction_id.astype(str).values[:-1]))

239260	236098	239318	236097

In [36]:
df3.auction_id.astype(str).iloc[-1] + '-1 ' + ' '.join([f'{x}-0' for x in negative])

'236099-1 229168-0 226138-0 231424-0 228963-0 226605-0 231221-0 253910-0 250422-0 242921-0 244865-0'

In [40]:
pd.DataFrame({'user_id': ['Joshua982'], 'history': [' '.join(df3.auction_id.astype(str).values[:-1])],
              'impression': [df3.auction_id.astype(str).iloc[-1] + '-1 ' + ' '.join([f'{x}-0' for x in negative])]})

,user_id,history,impression
0,Joshua982,239260 236098 239318 236097,236099-1 252893-0 233372-0 231439-0 250036-0 2...

In [ ]:
df.apply